include: package:effective_dart/analysis_options.1.3.0.yaml

analyzer:
  strong-mode: true
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/generated/**
    - lib/**/video_call.dart
    - lib/**/voice_call.dart
  errors:
    missing_required_param: error

linter:
  rules:
    constant_identifier_names: false
    public_member_api_docs: false
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false
    prefer_mixin: false
    type_annotate_public_apis: false
    lines_longer_than_80_chars: false
