name: flutter_social_messenger
description: A new Flutter application.

version: 1.0.4+7

environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  fast_i18n: 1.7.0

  #UI
  cupertino_icons: 1.0.0
  font_awesome_flutter: 8.9.0
  cached_network_image: 2.3.2+1
  shimmer: 1.1.1
  badges: 1.1.3
  awesome_dialog: ^1.2.0
  bubble: 1.1.9+1
  photo_view: 0.10.2
  bot_toast: 3.0.4
  flutter_staggered_grid_view: 0.3.2
  popup_menu: 1.0.5
  flare_flutter: 2.0.6
  flutter_widgets: 0.1.12
  google_fonts: 1.1.0
  pull_to_refresh: 1.6.2
  styled_widget: 0.2.2
  flutter_pagewise: 1.2.3
  uic: 0.5.0
  flutter_spinkit: 4.1.2+1
  pin_code_fields: 5.2.0
  flappy_search_bar: 1.7.2
  settings_ui: 0.4.0
  day_night_switcher: 0.1.1+1
  auto_size_text: 2.1.0
  rate_my_app: 0.7.2

  #State Managment
  flutter_modular: 2.0.1
  mobx: 1.2.1+2
  flutter_mobx: 1.1.0+2
  freezed_annotation: 0.12.0

  #Firebase
  firebase_core: 0.5.0
  firebase_auth: 0.18.1+1
  cloud_firestore: 0.14.1+2
  firebase_database: 4.1.0
  firebase_analytics: 6.0.1
  firebase_storage: 4.0.1
  firebase_messaging: 7.0.2
  firebase_crashlytics: 0.2.1
  cloud_functions: 0.6.0+1
  firebase_admob: 0.10.0

  shared_preferences: 0.5.12
  json_annotation: 3.1.0
  meta:
  logger: 0.9.4
  intl: 0.16.1
  timeago: 2.0.27
  path_provider: 1.6.18
  image_picker: 0.6.7+11
  url_launcher: 5.7.2
  permission_handler: 5.0.1+1
  flutter_cache_manager: 1.4.2
  flutter_ringtone_player: 2.0.0
  country_pickers: 1.3.0
  email_validator: 1.0.6
  profanity_filter: 1.0.4
  wallpaper_manager: 1.0.10
  flutter_sim_country_code: 0.0.3
  image_downloader: 0.20.1

  #call
  agora_rtc_engine: ^3.1.4
  flutter_callkeep: ^0.1.8

  #purchase
  in_app_purchase: ^0.3.4+16




dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
  build_runner: ^1.10.2
  freezed: ^0.12.1
  json_serializable: ^3.5.1
  mobx_codegen: ^1.1.2
  flutter_launcher_icons: ^0.8.1



flutter_icons:
  android: true
  ios: true
  image_path: "res/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - res/
    - res/images/

scripts: derry.yaml
